[package]
name = "aoc-8-2"
version = "0.1.0"
authors = ["Quodss <afoninkir170697@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
itertools = "0.10"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
